CMDB/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('unlogindex/', views.unlogindex, name='unlogin'),
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('index/', views.index),
    path('logout/',views.logout,name='logout'),
    path('renew/',views.renew,name='renew'),
    path('add/',views.add,name='add'),
]

pharmacy_CMDB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('CMDB.urls'), name='index'),
    path('login/', include('CMDB.urls'),name='login'),
    path('unlogindex/', include('CMDB.urls'),name='unlogin'),
    path('register/', include('CMDB.urls'),name='register'),
    path('index/',include('CMDB.urls')),
    path('logout/',include('CMDB.urls'),name='logout'),
    path('renew/',include('CMDB.urls'),name='renew'),
    path('add/',include('CMDB.urls'),name='add'),
    path('admin/', admin.site.urls),
]

CMDB/models.py
from django.db import models
#from django.contrib.auth.models import  User
# Create your models here.

class AsSet(models.Model):
    #共用部分
        
    asset_status = (
        (0,'正常未使用'),
        (1,'故障'),
        (2,'备用'),
        (3,'未知'),
        (4,'使用中'),
    )# 状态

    sn = models.CharField(
        max_length = 128,
        unique = True,
        verbose_name = '编号'
    )#唯一

    called = models.CharField(
        max_length= 64,
        verbose_name = '名称',
        null = True,
        blank = True,
    ) 

    status = models.SmallIntegerField(
        choices = asset_status,
        default = 0,
        verbose_name = '状态'
    )#选项

    indate = models.DateField(
        null = True,
        blank = True,
        verbose_name = '入库日期'
    )

    expiredate = models.DateField(
        null = True,
        blank = True,
        verbose_name = '过期时间'
    )
    
    manufacturer = models.ForeignKey(
        'Manufacturer',
        null = True,
        blank = True,
        verbose_name = '制造商',
        on_delete = models.SET_NULL
    )

    manager = models.ForeignKey(
        'User',
        null = True,
        blank = True,
        verbose_name = '管理者',
        related_name = 'aadmin',
        on_delete = models.SET_NULL
    )

    manageIP = models.GenericIPAddressField(
        null = True,
        blank = True,
        verbose_name = '管理IP'
    )

    house = models.ForeignKey(
        'House',
        null = True,
        blank = True,
        verbose_name = '实验楼',
        on_delete = models.SET_NULL
    )

    room = models.ForeignKey(
        'Room',
        null = True,
        blank = True,
        verbose_name = '房间号',
        on_delete = models.SET_NULL
    )

    x_locations = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        verbose_name='定位信息X'
    )

    y_locations = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        verbose_name='定位信息Y'
    )

    z_locations = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        verbose_name='定位信息Z'
    )

    memo = models.TextField(
        null = True,
        blank = True,
        verbose_name = '备注'
    )

    def __str__(self):
        return self.sn
    
    class Meta:
        verbose_name = '资产总表'
        verbose_name_plural = '总表'
        ordering = ['-sn']

class Manufacturer(models.Model):
      
    name = models.CharField(
        verbose_name = '厂商名称',
        max_length = 254,
        unique = True
    )
        
    phone =  models.CharField(
        verbose_name = '电话',
        max_length = 30,
        null = True,
        blank = True
    )

    def __str__(self):
        return self.name
       
    class Meta:
        verbose_name = '厂商'
        verbose_name_plural = '厂商'

class Room(models.Model):

    RoomNum = models.IntegerField(
        null = True,
        blank = True
    )

    def __str__(self):
        temp = str(self.RoomNum)
        return temp
        
    class Meta:
        verbose_name = '房间号'
        verbose_name_plural = '房间号'

class House(models.Model):
    detials = ""

    stand = (
        (0,'奉贤校区'),
        (1,'徐汇校区'),
        (2,'金山校区'),
    )

    WhereStand = models.SmallIntegerField(
        choices = stand,
        default = 0,
        verbose_name = '校区'
    )#选项

    HouseNumber = models.IntegerField(
        default = 1,
        verbose_name = '实验楼号'
    )
     
    def __str__(self):
        temps = self.stand[int(self.WhereStand)]
        temp = temps[-1]
        self.detials = str(temp)+str(self.HouseNumber)+"号楼"
        return self.detials
        
    class Meta:
        verbose_name = '校区+实验楼'
        verbose_name_plural = '校区'

class User(models.Model):
    name = models.CharField(max_length=64, unique=True)
    password = models.CharField(max_length=254)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = '用户基本信息'
        verbose_name_plural = '用户基本信息'

CMDB/forms.py
from django import forms

class UserForm(forms.Form):
    username = forms.CharField(label='用户名', max_length=64)
    password = forms.CharField(label='密码', max_length=254, widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    username = forms.CharField(label='用户名',max_length=64, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=254, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=254, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class AddForm(forms.Form):
    sn = forms.CharField(label='资产编号',max_length=127, widget=forms.TextInput(attrs={'class': 'form-control'}))
    called = forms.CharField(label='名称',max_length=63)
    status = forms.IntegerField(label='状态')
    manufacturer = forms.CharField(label='制造商')
    memo = forms.CharField(label='备注',max_length=254)
    indate = forms.DateField(label='入库')
    expiredate = forms.DateField(label='出库')
    house = forms.CharField(label='实验楼')
    room = forms.CharField(label='房间')

class RenewForm(forms.Form):
    called = forms.CharField(label='名称')

CMDB/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import models, forms
import hashlib
import time
# Create your views here.

def hashpass(username,password):
    md5 = hashlib.md5()
    sha256 = hashlib.sha256()
    md5.update(username.encode())
    salt = md5.hexdigest()
    password = password + salt
    sha256.update(password.encode())
    return sha256.hexdigest()

def get_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]#所以这里是真实的ip
    else:
        ip = request.META.get('REMOTE_ADDR')#这里获得代理ip
    return ip

def index(request):
    if not request.session.get('is_login',None):
        return redirect('/unlogindex/')
    assets = models.AsSet.objects.all()
    nowpage = '资产总表页'
    page = '资产总表页'
    return render(request,'CMDB/index.html',locals())

def unlogindex(request):
    if request.session.get('is_login',None):
        return redirect('/index/')
    return render(request,'CMDB/unlogindex.html')

def login(request):
    if request.session.get('is_login',None):
        return redirect('/index/')
    if request.method == 'POST':
        login_form = forms.UserForm(request.POST)
        message = "请检查填写内容"
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')
            try:
                user = models.User.objects.get(name=username)
            except:
                message = "用户不存在"
                return render(request, 'CMDB/login.html', locals())
            if user.password == hashpass(username,password):
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = user.name
                return redirect('/index/')
            else:
                message = '密码错误'
                return render(request,'CMDB/login.html', locals())
    login_form = forms.UserForm()
    return render(request,'CMDB/login.html', locals())

def register(request):
    if request.session.get('is_login',None):
        return redirect('/index/')
    if request.method == 'POST':
        requester_form = forms.RegisterForm(request.POST)
        message = "请检查填写内容"
        if requester_form.is_valid():
            username = requester_form.cleaned_data.get('username')
            password1 = requester_form.cleaned_data.get('password1')
            password2 = requester_form.cleaned_data.get('password2')
            if password1 != password2:
                message = '两次密码不同'
                return render(request,'CMDB/register.html',locals())
            else:
                same_name_user = models.User.objects.filter(name=username)
                if same_name_user:
                    message = "用户已存在"
                    return render(request, "CMDB/register.html", locals())
                new_user = models.User()
                new_user.name = username
                new_user.password = hashpass(username,password2)
                new_user.save()
                
                return redirect('/login/')
        else:
            return render(request, 'CMDB/register.html',locals())
    requester_form = forms.RegisterForm()
    return render(request,'CMDB/register.html',locals())

def logout(request):
    if not request.session.get('is_login', None):
        return redirect("/login/")
    request.session.flush()
    return redirect("/login/")

def renew(request):
    if not request.session.get('is_login',None):
        return redirect('/unlogindex/')
    if request.method =='POST':
        requester_form = forms.RenewForm(request.POST)
    sn = request.session['sn']
    others = models.AsSet.objects.get(sn=sn)
    manufacturers = models.Manufacturer.objects.all()
    houses = models.House.objects.all()
    rooms = models.Room.objects.all()
    nowpage = '信息更新'
    page = '信息更新'
    return render(request,'CMDB/renew.html',locals())

def add(request):
    if not request.session.get('is_login',None):
        return redirect('/unlogindex/')
    if request.method =='POST':
        requester_form = forms.AddForm(request.POST)
        message = "检查填写内容"
        if requester_form.is_valid():
            sn = requester_form.cleaned_data.get('sn')
            called = requester_form.cleaned_data.get('called')
            manageIP = get_ip(request)
            indate = requester_form.cleaned_data.get('indate')
            expiredate = requester_form.cleaned_data.get('expiredate')
            status = requester_form.cleaned_data.get('status')
            memo = requester_form.cleaned_data.get('memo')
            manufacturer = requester_form.cleaned_data.get('manufacturer')
            house = requester_form.cleaned_data.get('house')
            room = requester_form.cleaned_data.get('room')
            if sn == "":
                message = '编码为必填项'
            else:
                same_sn = models.AsSet.objects.filter(sn=sn)
                if same_sn:
                    message = "更新请使用更新选项"
                    request.session['sn'] = sn
                    return redirect('/renew/')
                new_thing = models.AsSet()
                new_thing.sn = sn
                new_thing.called = called
                new_thing.manageIP = manageIP
                new_thing.indate = indate
                new_thing.expiredate = expiredate
                new_thing.memo = memo
                new_thing.status = status
                #new_thing.manufacturer = manufacturer
                #new_thing.house = house
                #new_thing.room = room
                new_thing.save()
                return redirect('/add/')
        else:
            return render(request,'/add/',locals())
    requester_form = forms.AddForm()
    manufacturers = models.Manufacturer.objects.all()
    houses = models.House.objects.all()
    rooms = models.Room.objects.all()
    nowpage = '新增页'
    page = '新增页'
    return render(request,'CMDB/add.html',locals())

CMDB/templates/CMDB/add.html
{% extends "CMDB/loged.html" %}

{% block card1title %}{% endblock card1title%}

{% block card1text %}
        <form class="form-group" action="/add/" method="post">
            {% if message %}
                <div class="=alert-warning">{{message}}</div>
            {% endif %}
            {% csrf_token %}
            <div class="form-group">
                <label for="id_sn">编码</label>
                <input type="text" name="sn" class="form-group" id="id_sn" placeholder="资产编码" autofocus required>
            </div>
            <div class="form-group">
                <label for="id_called">名称</label>
                <input type="text" name="called" class="form-group" id="id_called" placeholder="资产名称" required>
            </div>
            <div class="form-group">
                <label for="id_status">状态</label>
                <select name='status'>
                    <option value="0" >正常未使用</option>
                    <option value="1" >故障</option>
                    <option value="2" >备用</option>
                    <option value="3" >未知</option>
                    <option value="4" selected>使用中</option>
                </select>
            </div>
            <div class="form-group">
                <label for="id_manufacturer">制造商</label>
                <select name='manufacturer'>
                {% for manufacturer in manufacturers %}
                    <option value="{{manufacturer.id}}">{{manufacturer}}</option>
                {% endfor %}
                </select>
            </div>            
            <div class="form-group">
                <label for="id_indate">入库时间</label>
                <input type="date" name="indate" class="form-group" id="id_indate" placeholder="入库时间" required>
            </div>
            <div class="form-group">
                <label for="id_expiredate">过期时间</label>
                <input type="date" name="expiredate" class="form-group" id="id_expiredate" placeholder="出库时间" required>
            </div>
            <div>
                <div class="form-group">
                    <label for="id_house">实验楼</label>
                    <select name=house>
                    {% for house in houses %}
                        <option value="{{house.id}}">{{house}}</option>
                    {% endfor %}
                    </select>
            </div>
            <div>
                <div class="form-group">
                    <label for="id_room">实验室号</label>
                    <select name=room>
                    {% for room in rooms %}
                        <option value="{{room.id}}">{{room}}</option>
                    {% endfor %}
                    </select>
            </div>
            <div class="form-group">
                <label for="id_memo">备注</label>
                <input type="text" name="memo" class="form-group" id="id_memo" placeholder="备注">
            </div>
            <div>
                <button type="submit" class="btn btn-primary float-right">提交</button>
            </div>
        </form>
{% endblock card1text%}

{% block elsecard %}{% endblock elsecard %}

{% block card2 %}{% endblock card2%}

{% block script %}
    {% autoescape off %}
    <script>
        $(function () {
                $('#assets_table').DataTable({
                  "paging": true,
                  "lengthChange": true,
                  "searching": true,
                  "ordering": true,
                  "info": true,
                  "autoWidth": true
                });
              });
        </script>
    {% endautoescape %}
{% endblock script %}

CMDB/templates/CMDB/index.html
{% extends "CMDB/loged.html" %}

{% block otherpage %}{% endblock otherpage %}

{% block card1title %}{% endblock card1title%}

{% block elsecard %}{% endblock elsecard %}

{% block card2 %}{% endblock card2%}

{% block card1text %}
    {% autoescape off %}
<section class="content">
    <div class="row">
      <div class="col-xs-12">
      <div class="box">
      <div class="box-header">
        <h3 class="box-title">资产总表</h3>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table id="assets_table" class="table table-bordered table-striped">
          <thead>
          <tr>
            <th>序号</th>
            <th>资产标号</th>
            <th>资产名称</th>
            <th>状态</th>
            <th>实验楼</th>
            <th>房间号</th>
            <th>入库日期</th>
            <th>过期时间</th>
            <th>制造商</th>
          </tr>
          </thead>
          <tbody>
            {% for asset in assets %}
            <tr>
                <td>{{ forloop.counter}}</td>
                <td>{{asset.sn}}</td>
                <td>{{asset.called}}</td>
                <td>{{asset.get_status_display}}</td>
                <td>{{asset.house}}</td>
                <td>{{asset.room}}</td>
                <td>{{asset.indate | date:"Y/m/d"}}</td>
                <td>{{asset.expiredate | date:"Y/m/d"}}</td>
                <td>{{asset.manufacturer}}</td>
            {% endfor %}
        </tbody>
    </table>

    {% endautoescape %}
{% endblock card1text%}

{% block script %}
    {% autoescape off %}
    <script>
        $(function () {
                $('#assets_table').DataTable({
                  "paging": true,
                  "lengthChange": true,
                  "searching": true,
                  "ordering": true,
                  "info": true,
                  "autoWidth": true
                });
              });
        </script>
    {% endautoescape %}
{% endblock script %}

CMDB/templates/CMDB/loged.html
{% extends "CMDB/base.html" %}

{% block notices %}{% endblock notices %}

{% block linkofnamelogin %}{% endblock linkofnamelogin %}

{% block namelogin %}{{request.session.user_name}}{% endblock namelogin %}

{% block titleofmain %}欢迎{{request.session.user_name}} 
<a href='/add/'>新增</a>{% endblock titleofmain %}

{% block rightdown %}欢迎使用本系统{% endblock rightdown %}

{% block rightside %}{% endblock rightside%}

{% block nowpage %}{{nowpage}}{% endblock nowpage %}

{% block page %}{{page}}{%endblock page%}

{% block search %}{% endblock search %}

CMDB/templates/CMDB/login.html
{% extends "CMDB/unlogindex.html" %}

{% block linkofnamelogin %}{% endblock linkofnamelogin %}

{% block namelogin %}{% endblock namelogin %}

{% block titleofmain %}登录测试{% endblock titleofmain %}

{% block card1title %}欢迎登录{% endblock card1title%}

</div>
{% block card1text %}
    {% autoescape off %}
</br>
</br>
        <form class="form-login" action="/login/" method="POST">
            {% if message %}
                <div class="alert alert-warning">{{message}}</div>
            {% endif %}
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username">用户名</label>
                <input type="text" name="username" class="form-group" id="id_username" placeholder="用户名" autofocus required>
            </div>
            <div class="form-group">
                <label for="id_password">密码</label>
                <input type="password" name="password" class="form-control" id="id_password" placeholder="Password" required>
            </div>
            <div>
                <a href="/register/" class="text-success " ><ins>新用户注册</ins></a>
                <button type="submit" class="btn btn-primary float-right">登录</button>
            </div>
        </form>
    {% endautoescape %}
{% endblock card1text%}
{% block page %}登录页面{% endblock page %}

CMDB/templates/CMDB/register.html
{% extends "CMDB/unlogindex.html" %}

{% block linkofnamelogin %}{% endblock linkofnamelogin %}

{% block namelogin %}{% endblock namelogin %}

{% block titleofmain %}注册测试{% endblock titleofmain %}

{% block card1title %}欢迎注册{% endblock card1title%}

{% block card2 %}{% endblock card2%}

{% block card1text %}
    {% autoescape off %}
</br>
</br>
        <form class="form-register" action="/register/" method="post">
            {% if message %}
                <div class="alert alert-warning">{{message}}</div>
            {% endif %}
            {% csrf_token %}
                <div class="form-group">
                    <label for="id_username">用户名</label>
                    <input type="text" name="username" class="form-group" id="id_username" placeholder="Username" autofocus required>
                </div>
                <div class="form-group">
                    <label for="id_password">密码</label>
                <input type="password" name="password1" class="form-control" id="id_password" placeholder="Password" required>
                </div>
                <div class="form-group">
                    <label for="id_password">确认密码</label>
                <input type="password" name="password2" class="form-control" id="id_password" placeholder="Password" required>
                </div>
                <div>
                    <a href="/login/"  ><ins>直接登录</ins></a>
                    <button type="submit" class="btn btn-primary float-right">注册</button>
                </div>
        </form>
    {% endautoescape %}
{% endblock card1text%}

{% block page %}注册页面{% endblock page %}

CMDB/templates/CMDB/renew.html
{% extends "CMDB/loged.html" %}

{% block card1title %}更新信息页面{% endblock card1title%}

{% block elsecard %}{% endblock elsecard %}

{% block card2 %}{% endblock card2%}

{% block card1text %}
<br>
<form class="form-group" action="/add/" method="post">
  {% if message %}
      <div class="=alert-warning">{{message}}</div>
  {% endif %}
  {% csrf_token %}
  <div class="form-group">
      <label for="id_sn">编码</label>
      <input type="text" name="sn" class="form-group" id="id_sn" placeholder="资产编码" readonly="true" value="{{sn}}">
  </div>
  <div class="form-group">
      <label for="id_called">名称</label>
      <input type="text" name="called" class="form-group" id="id_called" placeholder="资产名称" required value="{{others.called}}">
  </div>
  <div class="form-group">
      <label for="id_status">状态</label>
      <select name="thingsStatus" id="id_thingsStatus">
          <option value="0">正常未使用</option>
          <option value="1">故障</option>
          <option value="2">备用</option>
          <option value="3">未知</option>
          <option value="4" selected>使用中</option>
      </select>
  </div>
  <div class="form-group">
      <label for="id_manufacturer">制造商</label>
      <select>
      {% for manufacturer in manufacturers %}
          <option value="{{manufacturer}}">{{manufacturer}}</option>
      {% endfor %}
      </select>
  </div>            
  <div class="form-group">
      <label for="id_indate">入库时间</label>
      <input type="date" name="indate" class="form-group" id="id_indate" placeholder="入库时间" required>
  </div>
  <div class="form-group">
      <label for="id_expiredate">过期时间</label>
      <input type="date" name="expiredate" class="form-group" id="id_expiredate" placeholder="出库时间" required>
  </div>
  <div>
      <div class="form-group">
          <label for="id_house">实验楼</label>
          <select>
          {% for house in houses %}
              <option value="{{house}}">{{house}}</option>
          {% endfor %}
          </select>
  </div>
  <div>
      <div class="form-group">
          <label for="id_room">实验室号</label>
          <select>
          {% for room in rooms %}
              <option value="{{room}}">{{room}}</option>
          {% endfor %}
          </select>
  </div>
  <div class="form-group">
      <label for="id_memo">备注</label>
      <input type="text" name="memo" class="form-group" id="id_memo" placeholder="备注">
  </div>
  <div>
      <button type="submit" class="btn btn-primary float-right">提交</button>
  </div>
</form>
{% endblock card1text%}
{% block script %}
    {% autoescape off %}
    <script>
        $(function () {
                $('#assets_table').DataTable({
                  "paging": true,
                  "lengthChange": true,
                  "searching": true,
                  "ordering": true,
                  "info": true,
                  "autoWidth": true
                });
              });
        </script>
    {% endautoescape %}
{% endblock script %}

CMDB/templates/CMDB/unlogindex.html
{% extends "CMDB/index.html" %}

{% block search %}{% endblock search %}

{% block notices %}{% endblock notices %}

{% block linkofnamelogin %}/login/{% endblock linkofnamelogin %}

{% block namelogin %}游客{% endblock namelogin %}

{% block titleofmain %}尚未登录，仅做演示{% endblock titleofmain %}

{% block logout %}{% endblock logout %}

{% block page %}未登录{% endblock page %}

{% block elsecard %}{% endblock elsecard %}